---
dist: xenial
sudo: required
language: ruby
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install:
  - docker-compose up -d
  - function pg_ping { PGPASSWORD=postgres pg_isready -U postgres -h 127.0.0.1 -p 12345 >/dev/null 2>/dev/null; }
  - for i in {1..60}; do pg_ping && break; sleep 1; done
script:
  - bundle exec rake
gemfile:
  - gemfiles/ar42.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
env:
  matrix:
    - ARPROXY=0
    - ARPROXY=1
addons:
  apt:
    packages:
      - postgresql
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/ar60.gemfile
