---
dist: xenial
sudo: required
language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.3
  - 2.6.3
before_install:
  - docker-compose up -d
  - function pg_ping { PGPASSWORD=password pg_isready -U postgres -h 127.0.0.1 -p 15442; }
  - for i in {1..60}; do pg_ping && break; sleep 1; done
script:
  - bundle exec rake
gemfile:
  - gemfiles/ar42.gemfile
  - gemfiles/ar50.gemfile
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
addons:
  apt:
    packages:
      - postgresql
